### ISSUE TITLE
[css]两种盒模型说一下？

### ISSUE THREAD

**Issue by zhuanghaixin** [zhuanghaixin/Interview#43]

**Comment by zhuanghaixin** [comment]
# 标准盒模型
- 元素宽度=width
- 盒子总宽度 = width + padding + border + margin
# IE盒模型
- 元素宽度 = width + padding + border
- 盒子总宽度 = 元素宽度 + margin
# 为了简单地规避元素盒模型大小可变性造成的网页排版问题，一般我们会在样式重置的规则中，将盒模型设置成 border-box
```css
*, *:before, *:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```
- 盒子总宽度 = width

**Comment by zhuanghaixin** [comment]
# 将全局盒模型修改为border-box的弊端
如果在网页中使用了带样式的第三方组件，就可能会因此破坏其中一些组件的布局，尤其是当第三方组件在开发CSS的过程中没有考虑到使用者会修改盒模型时。因为全局设置border-box时使用的通用选择器会选中第三方组件内的每个元素，修改盒模型可能会有问题，所以最终需要写另外的样式将组件内的元素恢复为content-box。

**Comment by zhuanghaixin** [comment]
# 盒模型不会被继承，但是可以用inherit关键字强制继承
# 建议开发一个新的网站，使用以下css
```css
    :root {
      box-sizing: border-box;
    }

    *,
    ::before,
    ::after {
      box-sizing: inherit;
    }
```
