### ISSUE TITLE
[css] 如何在两列之间加间距

### ISSUE THREAD

**Issue by zhuanghaixin** [zhuanghaixin/Interview#51]
# 错误答案
```html
<!doctype html>
<head>
  <style>
    :root {
      box-sizing: border-box;
    }

    *,
    ::before,
    ::after {
      box-sizing: inherit;
    }

    body {
      background-color: #eee;
      font-family: Helvetica, Arial, sans-serif;
    }

    header {
      color: #fff;
      background-color: #0072b0;
      border-radius: .5em;
    }

    .main {
      float: left;
      width: 70%;
      background-color: #fff;
      border-radius: .5em;
    }

    .sidebar {
      float: left;
      width: 29%;
      margin-left: 1%;
      padding: 1.5em;
      background-color: #fff;
      border-radius: .5em;
    }

  </style>
</head>

<body>
  <header>
    <h1>Franklin Running Club</h1>
  </header>
  <div class="container">
    <main class="main">
      <h2>Come join us!</h2>
      <p>
        The Franklin Running club meets at 6:00pm every Thursday
        at the town square. Runs are three to five miles, at your
        own pace.
      </p>
    </main>
    <aside class="sidebar">
      <div class="widget"></div>
      <div class="widget"></div>
      <div class="gizmo"></div>
    </aside>
  </div>
</body>

```
# 百分比是相对于父元素的完整宽度的。如果想用其他单位指定间距呢？（我更想用em指定间距，因为em单位的一致性更好。）可以用calc()来实现
```css
    .main {
      float: left;
      width: 70%;
      background-color: #fff;
      border-radius: .5em;
    }

    .sidebar {
      float: left;
      width: calc(30% - 1.5em);
      margin-left: 1.5em;
      padding: 1.5em;
      background-color: #fff;
      border-radius: .5em;
    }
```
