### ISSUE TITLE
[css] css表格布局

### ISSUE THREAD

**Issue by zhuanghaixin** [zhuanghaixin/Interview#52]

**Comment by zhuanghaixin** [comment]
```html
  <div class="wrapper">
      <div class="container">
    
      <main class="main">
        <h2>Come join us!</h2>
        <p>
          The Franklin Running club meets at 6:00pm every Thursday
          at the town square. Runs are three to five miles, at your
          own pace.
        </p>
      </main>
      <aside class="sidebar">
        <div class="widget">1</div>
        <div class="widget">2</div>
        <div class="gizmo">3</div>
      </aside>
    </div>
  </div>
```
```css
    :root {
      box-sizing: border-box;
    }
    *,
    ::before,
    ::after {
      box-sizing: inherit;
    }
    body {
      background-color: #eee;
      font-family: Helvetica, Arial, sans-serif;
    }
    .wrapper {
      margin-left: -1.5em;
      margin-right: -1.5em;
    }
    .container {
      display: table;
      width: 100%;
      border-spacing: 1.5em 0;
    }
    .main {
      display: table-cell;
      width: 70%;
      background-color: #fff;
      border-radius: .5em;
    }
    .sidebar {
      display: table-cell;
      width: 30%;
      /* margin-left: 1.5em; */
      
      padding: 1.5em;
      background-color: #f00;
      border-radius: .5em;
    }
```
