### ISSUE TITLE
[css] line-height的使用

### ISSUE THREAD

**Issue by zhuanghaixin** [zhuanghaixin/Interview#55]
# 行高 line-height
line-height由上间距+文字大小+下间距组成
```css
p{
  font-size:16px;
  line-height:26px;
}
```
p的上间距是5px,文字大小16px,下间距是5px。
所以垂直居中就可以设置，height和line-height相同
