### ISSUE TITLE
[vue] 如何进行移动端的适配

### ISSUE THREAD

**Issue by zhuanghaixin** [zhuanghaixin/Interview#89]
# rem适配
#   1rem  当前设计稿像素/10   
比如750  1rem就是75px  通过lessb
```css
  .rem(@height,@value){
    @{height}:@value/75
  }
  .box{
    background-color: #f00;
    .rem(width,375);
    .rem(height,88);
  }
```
#
